GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/6077b0749bf9d95a8f94178c

###

POST http://localhost:3000/subscribers
Content-Type:application/json

{
    "name":"Amazing",
    "subscribedToChannel":"Fireship"
}

###
DELETE http://localhost:3000/subscribers/6077ae73aacdec579a4bc0a0


###
PATCH http://localhost:3000/subscribers/6077b0749bf9d95a8f94178c
Content-Type:application/json

{
    "name":"Marvel"
}